version: '3'
services:
  memory_check:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/memory_check.bash
  test:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/test.bash
  bootstrap:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/bootstrap.bash
  build_daybreak:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/build.bash /app/src/main.day
  build_daybreak_test:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/build.bash /app/tests/test_main.day
  fix_ownership:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/fix_ownership.bash
  push_base:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    image: exokomodo/daybreak:base-latest
    build:
      context: .
    command: bash /app/compose_scripts/build.bash /app/src/main.day
  push_devcontainer:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    image: exokomodo/daybreak:devcontainer-latest
    build:
      context: .
