version: '3'
services:
  memory_check:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/memory_check.sh
  test:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/test.sh
  bootstrap:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/bootstrap.sh
  build_daybreak:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/build.sh /app/src/main.day
  build_daybreak_test:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/build.sh /app/tests/test_main.day
  fix_ownership:
    environment:
      - CC=${CC}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash /app/compose_scripts/fix_ownership.sh
