version: '3'
services:
  configure:
    build:
      context: .
    command: bash compose_scripts/configure.sh
    volumes:
      - .:/app
  test:
    build:
      context: .
    command: bash compose_scripts/test.sh
    volumes:
      - .:/app
  build_all:
    build:
      context: .
    command: bash compose_scripts/build.sh all
    volumes:
      - .:/app
  build_daybreak:
    build:
      context: .
    command: bash compose_scripts/build.sh daybreak
    volumes:
      - .:/app
  build_daybreak_test:
    build:
      context: .
    command: bash compose_scripts/build.sh daybreak_test
    volumes:
      - .:/app
  fix_ownership:
    build:
      context: .
    command: bash compose_scripts/fix_ownership.sh
    volumes:
      - .:/app