version: '3'
services:
  memory_check:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/memory_check.sh
  test:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/test.sh
  bootstrap:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/bootstrap.sh
  build_daybreak:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/build.sh ./src/main.day
  build_daybreak_test:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/build.sh ./tests/test_main.day
  fix_ownership:
    environment:
      - CC_COMPILER=${CC_COMPILER}
      - DAYBREAK_BOOTSTRAP=${DAYBREAK_BOOTSTRAP}
      - DAYBREAK_OUT=${DAYBREAK_OUT}
    build:
      context: .
    command: bash ./compose_scripts/fix_ownership.sh
