def COMPOSE_ARGS = '--build --abort-on-container-exit'

pipeline {
  agent any

  options {
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DAYBREAK_BOOTSTRAP = './bootstrap/linux/daybreak'
    DAYBREAK_OUT = './out'
    CICADA_PRD_BRANCH = 'main'
    CICADA_REGISTRY_PASSWORD = credentials('docker-password')
    CICADA_REGISTRY_USERNAME = credentials('docker-username')
    CICADA_NAME = 'daybreak'

    CICADA_ROOT_DIR = ".cicada"
    CICADA_HEAD_DIR = "${CICADA_ROOT_DIR}/.head"
    CICADA_CI_DIR = "${CICADA_HEAD_DIR}/ci"
    CICADA_PIPELINES_DIR = "${CICADA_ROOT_DIR}/pipelines"
    CICADA_DOCKER_HUB_DEV_PROJECT = 'development'
    CICADA_DOCKER_HUB_PRD_PROJECT = 'daybreak'
    CICADA_DOCKER_HUB_USERNAME = 'exokomodo'
    COMPOSE_FILE_ARG = "-f ${CICADA_PIPELINES_DIR}/${CICADA_NAME}/docker-compose.yaml"
  }

  stages {
    stage('docker login') {
      steps {
        sh "bash ${CICADA_CI_DIR}/container_login.bash"
      }
    }

    stage('gcc') {
      environment {
        CC_COMPILER = 'gcc'
      }
      parallel {
        stage('[gcc] Build Daybreak') {
          steps {
            sh "docker-compose ${COMPOSE_FILE} -p gcc-build up ${COMPOSE_ARGS} build_daybreak"
          }
        }

        stage('[gcc] Test') {
          steps {
            sh "docker-compose z${COMPOSE_FILE} -p gcc-test up ${COMPOSE_ARGS} test"
          }
        }

        stage('[gcc] Memory Check') {
          steps {
            sh "docker-compose ${COMPOSE_FILE} -p gcc-memcheck up ${COMPOSE_ARGS} memory_check"
          }
        }
      }
    }

    stage('clang') {
      environment {
        CC_COMPILER = 'clang'
      }
      parallel {
        stage('[clang] Build Daybreak') {
          steps {
            sh "docker-compose ${COMPOSE_FILE} -p clang-build up ${COMPOSE_ARGS} build_daybreak"
          }
        }

        stage('[clang] Test') {
          steps {
            sh "docker-compose ${COMPOSE_FILE} -p clang-test up ${COMPOSE_ARGS} test"
          }
        }

        stage('[clang] Memory Check') {
          steps {
            sh "docker-compose ${COMPOSE_FILE} -p clang-memcheck up ${COMPOSE_ARGS} memory_check"
          }
        }
      }
    }

    stage('zig') {
      environment {
        CC_COMPILER = 'zig'
      }
      parallel {
        stage('[zig] Build Daybreak') {
          steps {
            sh "docker-compose ${COMPOSE_FILE_ARG} -p zig-build up ${COMPOSE_ARGS} build_daybreak"
          }
        }

        stage('[zig] Test') {
          steps {
            sh "docker-compose ${COMPOSE_FILE_ARG} -p zig-test up ${COMPOSE_ARGS} test"
          }
        }

        stage('[zig] Memory Check') {
          steps {
            sh "docker-compose ${COMPOSE_FILE_ARG} -p zig-memcheck up ${COMPOSE_ARGS} memory_check"
          }
        }
      }
    }

    stage('zig-wasi') {
      environment {
        CC_COMPILER = 'zig-wasi'
      }
      parallel {
        stage('[zig-wasi] Build Daybreak') {
          steps {
            sh "docker-compose ${COMPOSE_FILE_ARG} -p zig-wasi-build up ${COMPOSE_ARGS} build_daybreak"
          }
        }

        stage('[zig-wasi] Test') {
          steps {
            sh "docker-compose ${COMPOSE_FILE_ARG} -p zig-wasi-test up ${COMPOSE_ARGS} test"
          }
        }
      }
    }
  }

  post {
    always {
      sh "docker-compose -f ${COMPOSE_FILE} up ${COMPOSE_ARGS} fix_ownership"
    }
    cleanup {
      sh "bash ${CICADA_CI_DIR}/cleanup.bash"
    }
  }
}
