def COMPOSE_ARGS = '--build --abort-on-container-exit'

pipeline {
	agent any

	options {
		disableConcurrentBuilds()
		ansiColor('xterm')
	}

	environment {
		DAYBREAK_BOOTSTRAP="./bootstrap/linux/daybreak"
		DAYBREAK_OUT="./out"
		CICADA_PROD_BRANCH="main"
		CICADA_REGISTRY_PASSWORD=credentials("docker-password")
		CICADA_REGISTRY_USERNAME=credentials("docker-username")
		CICADA_NAME="daybreak"
	}

	stages {
		stage('docker login') {
			steps {
				sh "bash ./cicada/ci/container_login.bash"
			}
		}

		stage('gcc') {
			environment {
				CC_COMPILER = "gcc"
			}
			parallel {
				stage ("[gcc] Build Daybreak") {
					steps {
						sh "docker-compose -p gcc-build up ${COMPOSE_ARGS} build_daybreak"
					}
				}
				
				stage('[gcc] Test') {
					steps {
						sh "docker-compose -p gcc-test up ${COMPOSE_ARGS} test"
					}
				}

				stage('[gcc] Memory Check') {
					steps {
						sh "docker-compose -p gcc-memcheck up ${COMPOSE_ARGS} memory_check"
					}
				}
			}
		}

		stage('clang') {
			environment {
				CC_COMPILER = "clang"
			}
			parallel {
				stage('[clang] Build Daybreak') {
					steps { 
						sh "docker-compose -p clang-build up ${COMPOSE_ARGS} build_daybreak"
					}
				}

				stage('[clang] Test') {
					steps {
						sh "docker-compose -p clang-test up ${COMPOSE_ARGS} test"
					}
				}
				
				stage('[clang] Memory Check') {
					steps {
						sh "docker-compose -p clang-memcheck up ${COMPOSE_ARGS} memory_check"
					}
				}
			}
		}

		stage('zig') {
			environment {
				CC_COMPILER = "zig"
			}
			parallel {
				stage('[zig] Build Daybreak') {
					steps { 
						sh "docker-compose -p zig-build up ${COMPOSE_ARGS} build_daybreak"
					}
				}

				stage('[zig] Test') {
					steps {
						sh "docker-compose -p zig-test up ${COMPOSE_ARGS} test"
					}
				}
				
				stage('[zig] Memory Check') {
					steps {
						sh "docker-compose -p zig-memcheck up ${COMPOSE_ARGS} memory_check"
					}
				}
			}
		}

                stage('zig-wasi') {
			environment {
				CC_COMPILER = "zig-wasi"
			}
			parallel {
				stage('[zig-wasi] Build Daybreak') {
					steps { 
						sh "docker-compose -p zig-wasi-build up ${COMPOSE_ARGS} build_daybreak"
					}
				}

				stage('[zig-wasi] Test') {
					steps {
						sh "docker-compose -p zig-wasi-test up ${COMPOSE_ARGS} test"
					}
				}
			}
		}
	}

	post {
		always {
			sh "docker-compose up ${COMPOSE_ARGS} fix_ownership"
		}
		cleanup {
			sh "bash ./cicada/ci/cleanup.bash"
		}
	}
}
